package com.autominutes.backend.service;

import com.autominutes.backend.dto.MeetingCreateRequest;
import com.autominutes.backend.dto.MeetingDTO;
import com.autominutes.backend.dto.MeetingUpdateRequest;

import java.util.List;
import java.util.Optional;

/**
 * Service for managing meetings (create, read, update, delete).
 * <p>
 */
public interface MeetingService {

    /**
     * Returns all meetings in the system.
     *
     * @return list of meetings mapped as {@link MeetingDTO}, may be empty if none exist
     */
    List<MeetingDTO> getAllMeetings();

    /**
     * Looks up a meeting by id.
     *
     * @param id the id of the meeting to look up
     * @return an {@link Optional} containing the meeting DTO if it exists, otherwise empty
     */
    Optional<MeetingDTO> getMeetingById(Long id);

    /**
     * Creates a new meeting from the given input data.
     *
     * @param request validated input data (title, description, date)
     * @return the newly created meeting, with the id generated by the database
     */
    MeetingDTO createMeeting(MeetingCreateRequest request);

    /**
     * Partially updates an existing meeting. Fields left unset (null) in the request
     * remain unchanged from their existing values in the database.
     *
     * @param id      the id of the meeting to update
     * @param request the fields to update (any null field is ignored)
     * @return the updated meeting
     * @throws com.autominutes.backend.exception.ResourceNotFoundException if no meeting exists with this id
     */
    MeetingDTO updateMeeting(Long id, MeetingUpdateRequest request);

    /**
     * Deletes a meeting. Due to the {@code ON DELETE CASCADE} relationships in the schema,
     * this also automatically deletes the associated transcript, attendee links, and AI results.
     *
     * @param id the id of the meeting to delete
     * @throws com.autominutes.backend.exception.ResourceNotFoundException if no meeting exists with this id
     */
    void deleteMeeting(Long id);
}